# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build app

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.txt"
      - .editorconfig
      - ".github/**"
      - .gitignore
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"
      - run: dotnet build dotnet-cross.csproj
        name: Build
  deploy:
    name: Publish application
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') && success()
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"
      - run: |
          echo "Github ref is: $GITHUB_REF"
          if [[ "$GITHUB_REF" =~ ^refs\/tags\/([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(\-[[:alpha:]])?)$ ]]; then
            echo "Version is: ${BASH_REMATCH[1]}"
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            >&2 echo "Not running for a tag. Is this a problem with Github Actions?"
            exit 1
          fi
        name: Prepare version number
      - run: dotnet pack -c Release dotnet-cross.csproj -p:Version=$VERSION
        name: Pack dotnet tool
      - name: Copy published files to publish location
        run: |
          mkdir publish
          cp bin/Release/dotnet-cross.$VERSION.nupkg publish/
          cp bin/Release/dotnet-cross.$VERSION.snupkg publish/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/*

      - name: Upload to GPR
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push bin/Release/*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }} -k ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload to NuGet
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: dotnet nuget push bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

